let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "OREO Chocolate Cookie",
    price: 20,
    desc: "Take a delicious break with OREO Chocolate Sandwich Cookies.",
    img: "images/img-1.png",
  },
  {
    id: "ioytrhndcv",
    name: "Black & White Cookies",
    price: 15,
    desc: "Milk’s Favorite Cookie Is Now Gluten Free OREO fans will celebrate,",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "OREO Gluten  Cookies",
    price: 35,
    desc: "The OREO Golden Sandwich cookie you know, and love is now a certified.",
    img: "images/img-3.jpg",
  },
  {
    id: "fhcbcv",
    name: "OREO Cookie Cakesters",
    price: 40,
    desc: "Milk’s Favorite Cookie Is Now Gluten Free OREO fans will celebrate this delightful.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "OREO iridescent Mug",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "OREO Cookie Flip Flops",
    price: 50,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "OREO Cake Candle",
    price: 55,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "OREO Cookie  Socks",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Cookie for Santa Fleece",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "OREO Twist,Lick. Tee",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "OREO Milk Duck Sweater",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Golden Cookie Candle",
    price: 60,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.jpg",
  },
];
